### ISSUE TITLE
桌面问题

### ISSUE THREAD

**Issue by stephen-android-dev** [rovast/oh-my-deepin#1]
嗨，你好，我最近刚刚装Deepin，我想问一下你的顶部任务栏是怎么实现的啊，还有你的桌面美化是怎么做的，能给点点提示吗？
非常感谢

**Comment by rovast** [comment]
截图中的顶部任务栏其实和 deepin 关系不大了。这个属于 gnome3 桌面系统的一个插件。

如果你愿意折腾的话，按如下步骤去尝试：
1. 安装 gnome3 桌面系统 `sudo apt-get install task-gnome-desktop `
2. 重启系统，选择 gnome 桌面进入
3. 安装 gnome3 拓展 [Unite](https://extensions.gnome.org/extension/1287/unite/)

安装后，可以在「优化工具」中进行配置
